# A basic redirect rule
[[redirects]]
  # from = "/*"
  # to = "https://api.thankyougift.io/graphql"
  # status = 200
  # force = true
  # headers = {X-From = "Netlify"}
  from = "/*"
  to = "/index.html"
  status = 200

# [[headers]]
#   for = "/*"
#     [headers.values]
#     Access-Control-Allow-Origin = "*"
